### ISSUE TITLE
Admin permissions for contextlib2

### ISSUE THREAD

**Issue by ncoghlan** [jazzband/roadies#100]
I just noticed I can't currently add new contributors for the contextlib2 repo when I went to send Yury an invite :)

**Comment by jezdez** [comment]
@ncoghlan Ah, all that is needed is to ask Yury to join Jazzband and he can contribute directly. I'm trying to not make exception to the way Jazzband works to not have to maintain a list of contributors and fall in the trap of nobody knowing who's admin currently like in a project separate from Jazzband.

Do you need Yury to have admin permissions? Do you need them?

**Comment by ncoghlan** [comment]
Ah, cool - in that case I'll just email him :)
