### ISSUE TITLE
Please add me as lead for django-configurations

### ISSUE THREAD

**Issue by blueyed** [jazzband/roadies#102]
https://github.com/jazzband/django-configurations/

I do not have permissions on PyPI for this project, so I cannot check if the jazzband user is there already.

(via https://jazzband.co/about/releases)

**Comment by blueyed** [comment]
PyPI appears to be setup already: https://github.com/jazzband/django-configurations/blob/ee43a1d872706fc6890ebde5c8478bfba7adfa18/.travis.yml#L74-L83

Can I somehow see who is lead for a project?

**Comment by jezdez** [comment]
There are no project leads for this project yet since nobody asked for it yet, I'll update the credentials accordingly and add you and me to it. Cheers!

**Comment by jezdez** [comment]
@blueyed See https://github.com/jazzband/django-configurations/commit/b43bf2dd47c7fc752e6fdaa317663cf6cdbbfdeb for the change needed. Sorry for the whitespace changes, but that's what the travis CLI did when I updated the encrypted password.

This will deploy the release to jazzband.co for new Git tags, then email the project leads and ask to confirm the release for security reasons. Please use your new powers with greatest care and let me know if you have any questions about the django-configurations API. For your recent merges I wish you would have pinged me and asked for my opinion before merging them. I trust that you will do so in the future, thanks!

**Comment by blueyed** [comment]
@jezdez 
Thanks!

So you want me to do the changes, since you reverted them already?

What do you think about using Travis stages for this?
https://github.com/pytest-dev/pytest-django/blob/f1bc02488049e6988f9299ddd7ca7e63bcd2f188/.travis.yml#L39-L51

**Comment by jezdez** [comment]
@blueyed Sorry, which changes do you mean?

Yeah, Travis stages are great for this, the travis config file can be moved over to it now that the stages have seen some use.

**Comment by blueyed** [comment]
@jezdez 
Oh, I was confused by https://github.com/jazzband/django-configurations/commit/537fde7f5b4cd7f42353d049ce06a6e440d5215c - but it is apparently empty.
