### ISSUE TITLE
Request lead for django-embed-video

### ISSUE THREAD

**Issue by mgrdcm** [jazzband/roadies#104]
Greetings!

`django-embed-video` needs some updates to be compatible with `Django>=2.1`.  I've got a couple PRs (https://github.com/jazzband/django-embed-video/pull/89 and then https://github.com/jazzband/django-embed-video/pull/88) to address the issues.  Could use some help doing a review on them if anyone would like but if not that's fine too, they're pretty straightforward.

And then would request lead access for the project to get that release out.  @CedricCarrard did the last changes, but there haven't been any updates in over a year now.

**Comment by aleksihakli** [comment]
Hey @mgrdcm, @CedricCarrard and @jezdez. I have some time opening up in the summer and autumn and can help out with [`django-embed-video`](https://github.com/jazzband/django-embed-video) maintenance. I've set up [`django-axes`](https://github.com/jazzband/django-axes) and am planning to improve the [`django-ical`](https://github.com/jazzband/django-axes). I've previously used `django-embed-video` so I do have some experience with it and the video embed APIs.

**Comment by aleksihakli** [comment]
@jezdez @CedricCarrard would you be OK with me as a maintainer for this project?

**Comment by jezdez** [comment]
That makes sense @mgrdcm, I've added you and @aleksihakli as project leads. Thank you!
