### ISSUE TITLE
Add pypi password to travis for django-robots

### ISSUE THREAD

**Issue by yakky** [jazzband/roadies#11]
django-robots 2.0 is ready for release, could you add the password for travis?

**Comment by jezdez** [comment]
done.

**Comment by jezdez** [comment]
In https://github.com/jazzband/django-robots/commit/903a22e2b6e2df0f38026e0bb49781a08fc83b91 for the record.

**Comment by yakky** [comment]
awesome! 2.0rc1 will come soon :)
