### ISSUE TITLE
Release permissions for the django-axes repository

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/roadies#112]
I think it would be reasonable to grant me or @markddavidoff release permissions on the django-axes project releases from the Jazzband repository to PyPI. I can work with @camilonova and @markddavidoff to update the project to PyPI and make new releases on it on peer reviewed content.

I am familiar with the Jazzband Code of Conduct and the PyPI release architecture as well as versioning schemes and contribute to a number of Python packages.

Refer to [#364](https://github.com/jazzband/django-axes/pull/364) for more information.

**Comment by jezdez** [comment]
@camilonova What say you?

**Comment by markddavidoff** [comment]
...

**Comment by camilonova** [comment]
@jezdez lets grant permissions to @aleksihakli

**Comment by jezdez** [comment]
@camilonova Done.

@aleksihakli On the next tag you'll get the regular release email along with @camilonova and will be asked to review and confirm the release before it's pushed to PyPI. Please make sure to read https://jazzband.co/about/releases. Thanks!

**Comment by aleksihakli** [comment]
OK, thanks @jezdez!
