### ISSUE TITLE
Please setup PyPI releases for django-redshift-backend

### ISSUE THREAD

**Issue by shimizukawa** [jazzband/roadies#114]
https://github.com/jazzband/django-redshift-backend/

refs: https://github.com/jazzband/roadies/issues/113

**Comment by shimizukawa** [comment]
@jezdez ping

**Comment by jezdez** [comment]
Sorry, on it.

**Comment by jezdez** [comment]
This is done.

When a Git tag is pushed and Travis passes, it'll do a release to the Jazzband site. You'll get an email asking for confirming the release (see email for steps to do that). Once that's done the release happens automatically to PyPI. Please let me know when you do the first release using that technique, so we can debug things if needed. Good luck!
