### ISSUE TITLE
Proposing django-analytical

### ISSUE THREAD

**Issue by jcassee** [jazzband/roadies#115]
[django-analytical](https://github.com/jcassee/django-analytical) is a Django package containing a set of template tags for quickly hooking up analytics services. Although it sees continuous development, I have been slower with pull request merges and releases than I would like. I hope that by transferring the project to Jazzband can share this responsibility.

Current Jazzband members @pjdelport and (recently :smile:) @bittner are also contributors to django-analytical.

**Comment by bittner** [comment]
Any opinions or updates on this?

**Comment by jezdez** [comment]
@jcassee This looks like a good candidate! Feel free to simply transfer the repo to the Jazzband organization, a ticket is created automatically with a TODO list to update the repo to follow the [Jazzband guidelines](https://jazzband.co/about/guidelines). Simply go to https://jazzband.co/, login and join Jazzband on your account dashboard. This will give you the required permissions to transfer the repo.

**Comment by jcassee** [comment]
Just transferred the repo!

**Comment by jcassee** [comment]
@jezdez Three tickets were opened (#116, #117 and #118). I'm only going to do this once! :stuck_out_tongue_winking_eye:

**Comment by jezdez** [comment]
Yeaaaaah. This is a long standing issue, sigh. The notification doesn't lock correctly. 😬

**Comment by jezdez** [comment]
I closed #117 and #118. Sorry for the noise.

**Comment by jezdez** [comment]
Fixed!
