### ISSUE TITLE
Question about code of Conduct

### ISSUE THREAD

**Issue by goinnn** [jazzband/roadies#121]
I have join to jazzband today. I have a PR in django-push-notification https://github.com/jazzband/django-push-notifications/pull/487 Is it ugly if now I accept this PR to myself?

**Comment by jleclanche** [comment]
I don't think there's a problem with you accepting your own PRs but you do need to address the issues brought up in previous reviews.

**Comment by jezdez** [comment]
Yeah, what @jleclanche said.

Jazzband members need to strive to be collaborative (probably more so than in other GitHub projects), so if another member for example has reviewed the code and you've made the requested adjustments (or simply got the go-ahead from the reviewer) it's okay to merge the PR yourself. A no-go would be ignoring the feedback from another member without providing legitimate reasons.

That said, if in doubt reach out to other members that have committed to the project or open a ticket here (like you did 👍).

Hope this clears things up!

**Comment by goinnn** [comment]
@jleclanche & @jezdez Thanks!
