### ISSUE TITLE
pip-tools doesn't work on travis-ci

### ISSUE THREAD

**Issue by atugushev** [jazzband/roadies#122]
Pip-tools seems to be disabled in Travis CI, for on the page https://travis-ci.org/jazzband/pip-tools has been told "This is not an active repository". It does not trigger a job anymore, see https://github.com/jazzband/pip-tools/pull/711.

Could someone fix it please?

**Comment by jezdez** [comment]
Probably related to https://changelog.travis-ci.com/migrating-from-github-services-to-webhooks-86328. I've re-activated it.

**Comment by atugushev** [comment]
Thanks! That helped.
