### ISSUE TITLE
Proposing django-taggit

### ISSUE THREAD

**Issue by jdufresne** [jazzband/roadies#123]
https://github.com/alex/django-taggit

I have received permission from @alex in an email to move the project to Jazzband and he is awaiting his instructions on what he must do to complete the move.

**Viability** - The project is well established and well used. It has been used by Django projects for quite some time. Its first documented release was 2010-06-22 and is still used today. GitHub stats: Watchers: 69, Stars: 2026, Forks: 488.

**Documentation** - https://django-taggit.readthedocs.io/en/latest/

**Tests** - It contains a comprehensive test suites: https://github.com/alex/django-taggit/tree/master/tests

**Conduct** - I'm happy to add the code of conduct. Shall this be done before or the transfer?

**Contributing Guidelines** - One exists, I'm happy to modify it to be in line with Jazzband. Shall this come before or after the transfer?

**Comment by jezdez** [comment]
Hi @jdufresne, @alex!

django-taggit sounds like a good match indeed, feel free to simply transfer the repo to the Jazzband repo.

To do that you'll have to (temporarily if you want) join the Jazzband on https://jazzband.co/join. You'll be added to the GitHub organization once you've consented to it and can very easily leave the organization again if you wish to do that.

Once the repo transfer has finished a new ticket will automatically created with a TODO list (there is a bug right now that possibly creates multiple tickets, just ignore the duplicates).

**Comment by alex** [comment]
Sounds good -- @jdufresne, I can't remember, do you have the permission to do the repo transfer, or am I needed for that?

**Comment by jdufresne** [comment]
@alex No, I do not have that permission at the moment so you'll need to do the actual transfer. Once transferred, I can follow through with all normal todo items. Thanks!

**Comment by alex** [comment]
Here we go: https://github.com/jazzband/django-taggit

Thanks so much for maintaing taggit over the years! And thanks for Jazz Band for continuing to look after it!

**Comment by jdufresne** [comment]
Thanks! I'll continue the effort by following the todo items in #126.
