### ISSUE TITLE
Proposing python-geojson

### ISSUE THREAD

**Issue by frewsxcv** [jazzband/roadies#129]
https://github.com/frewsxcv/python-geojson/

I don't work with Python regularly anymore, and no longer have time to maintain this project. Does Jazzband accept non-Django projects?

**Comment by jezdez** [comment]
@frewsxcv Absolutely! This looks pretty good, although it would be neat to have documentation on ReadTheDocs. Don't think it's a deal breaker though.

Basically all you have to do is, join Jazzband on https://jazzband.co/join (that adds you as a member to the Jazzband GitHub organization) and transfer the repo to the Jazzband GitHub organization using the [standard transfer workflow](https://help.github.com/articles/transferring-a-repository/#transferring-a-repository-owned-by-your-organization).

Once the repo has been transfered a new ticket is created with a TODO list to get the repo inline with the [Jazzband guidelines](https://jazzband.co/about/guidelines).

**Comment by frewsxcv** [comment]
https://github.com/jazzband/roadies/issues/132
