### ISSUE TITLE
Is django-salmonella a fit for jazzband?

### ISSUE THREAD

**Issue by ipmb** [jazzband/roadies#13]
https://github.com/lincolnloop/django-salmonella
https://pypi.python.org/pypi/django-salmonella

I can get it to meet the [Jazzband guidelines](https://jazzband.co/about/guidelines) if you feel like it is a fit.

**Comment by jezdez** [comment]
Yeah, the only thing I see is missing from the guidelines is automated testing, if you can add those I think it's good to go.

**Comment by bartTC** [comment]
i wasn't aware @ipmb proposed this but I think this is a good fit for this project. I took over the maintenanceship, cleaned it up, added testsuite, added Travis etc.

**Comment by bartTC** [comment]
I'd extend the docs and add contribution specific ones.

**Comment by jezdez** [comment]
Ok, where do we go from here?

**Comment by bartTC** [comment]
I will extend the docs and add contribution specific ones. Soon! 😄

**Comment by jezdez** [comment]
@bartTC Any news on this?

**Comment by bartTC** [comment]
I haven't managed to get into this and I dont think I will have time in near future. I'll close this request and will reopen it, once tests and docs are done.

Thanks for the patience @jezdez.

**Comment by bartTC** [comment]
Figured I can't close this myself, please do so @jezdez.

**Comment by jezdez** [comment]
Works for me, @bartTC!
