### ISSUE TITLE
Invitation not being sent

### ISSUE THREAD

**Issue by joshua-s** [jazzband/roadies#133]
When I attempt to send the invitation to join the Jazzband org, I am met with this screen:
![screenshot_2019-02-20 jazzband](https://user-images.githubusercontent.com/1479244/53103984-664c2e80-34e3-11e9-9be6-d8184ff5a35c.png)

I have 5 verified emails on my GitHub account (0 unverified).

**Comment by jezdez** [comment]
@joshua-s Could you try again, please?

**Comment by joshua-s** [comment]
@jezdez it worked, thanks!
