### ISSUE TITLE
Invitation not being sent

### ISSUE THREAD

**Issue by marfyl** [jazzband/roadies#134]
Hi! is there any problem with invitations? Im receiving this error

![image](https://user-images.githubusercontent.com/3458215/53609370-f1ee4b00-3bc6-11e9-9f53-5da577a51f79.png)

**Comment by jezdez** [comment]
@marfyl Hey, you closed it again, did it work for you eventually?

**Comment by marfyl** [comment]
I think it was just an edition of my answer @jezdez it's working. thanks

**Comment by KFoxder** [comment]
@marfyl I keep getting this message. When going to the URL: `https://jazzband.co/account/join`

Did you just try again later? 


![image](https://user-images.githubusercontent.com/2000316/53853300-e1f1b500-3f92-11e9-9600-9b50679867de.png)
