### ISSUE TITLE
email not fetched, invitation cannot be sent

### ISSUE THREAD

**Issue by MattBlack85** [jazzband/roadies#138]
for some reason the email address is not fetched from GH api (it's publicly available), here a screenshot so I cannot send the invitation.

![image](https://user-images.githubusercontent.com/4163222/54595376-c5de2100-4a32-11e9-942f-b67afd1047ea.png)

**Comment by jezdez** [comment]
Apologies for the slow reply, I've updated the code that fetches the email addresses from GitHub quite a bit to handle GitHub API rate limiting better and it should work better now. Try again by logging out and in again of the Jazzband site and it should successfully fetch the email addresses. If that doesn't help you could also try looking at the member team page at https://github.com/orgs/jazzband/teams/members/members if you see your invitation there.

**Comment by MattBlack85** [comment]
hey @jezdez thank you very much, can confirmed I am now part of the community!
