### ISSUE TITLE
Fussy Fox – real-time linter

### ISSUE THREAD

**Issue by codingjoe** [jazzband/roadies#139]
Hey there,

so there is service called [Fussy Fox](https://fussyfox.github.io/) which is like Travis-CI, except it runs static code linters on AWS lambda. It crazy fast and uses GitHubs new checks API.

I think this could be helpfull, I don't see why we need to setup linters in Travis-CI, plus this would give contributors fast and machine based feedback. I've been using this on a bunch of projects so far and am really happy with it.

If we enable it for jazzband, every repository can chose it own linters. The configuration is maintained in code. So there will be no supported needed from the roadies beyond authorizing the GitHub app once.

What do you think?

_Oh and yes, me and guys from work wrote Fussy Fox. Still makes it a good idea ;)_

**Comment by jezdez** [comment]
Neat, who's paying the AWS bills for it?

**Comment by jezdez** [comment]
Enabled it, let's see how it goes?

**Comment by codingjoe** [comment]
> Neat, who's paying the AWS bills for it?

Me, but it's still bearable. If it gets out of hand I'll look for a sponsor.

> Enabled it, let's see how it goes?

Can't hurt. Go for it!

**Comment by jezdez** [comment]
Closing this since this has been enabled and found useful. Thanks @codingjoe! Please let me know if there are any changes to FussyFox that would require us changing on the Jazzband side.

**Comment by codingjoe** [comment]
Will do, thanks!

**Comment by codingjoe** [comment]
@jezdez did you accept the updated permission request already? I am not sure it's running everywhere it should, and I am trying to find out if it's systemic or simply not installed.

**Comment by jezdez** [comment]
Sorry I was looking into permissions issues for org-wide apps and uninstalled the other day for Jazzband. That said looking back at the usage, I think it's never been adopted by enough projects to make a dent in ease of maintenance and I'm wondering if going with using GitHub actions for linting purposes would be more aligned with the goal of reducing maintenance burden. Do you have any news on your side how things are going?

**Comment by codingjoe** [comment]
> Sorry I was looking into permissions issues for org-wide apps and uninstalled it the other day for Jazzband.

So it is not installed? I just need to know because pip-tools somewhat relies on it.

> That said looking back at the usage, I think it's never been adopted by enough projects to make a dent in ease of maintenance and I'm wondering if going with using GitHub actions for linting purposes would be more aligned with the goal of reducing maintenance burden. Do you have any news on your side how things are going?

Yes, you make a good point. To be fair, the issue that I just now fixed was probably the biggest reason it hasn't been adapted. Until now, FussyFox didn't run on pull-requests unless the user had the app installed. Needless to say, that this was kind of pointless. No one adapted it, because they didn't even see the `Getting started`. I myself also didn't adapt it in more projects, because of that problem.

Now that issue is fixed, and I'd like to give it another chance. I do see your point with GitHub actions. I still believe static linters don't need adjustable environments. FussyFox is still loads faster than actions.
A nice side effect being, that it probably is better for the energy (CO2) footprint, besides it being more convenient for developers.

I am not yet drowning in AWS bills and I'd certainly like to give it another shot. I also really appreciate your help to support my pet project.
