### ISSUE TITLE
Setup django-taggit readthedocs

### ISSUE THREAD

**Issue by jdufresne** [jazzband/roadies#140]
I've been maintaining django-taggit.

I can't manage the project on readthedocs.org and it doesn't seem to be updated automatically after a release. What steps should I take to be able to manage the docs? If it makes a difference, my username is jdufresne on rtd. Thanks!

https://django-taggit.readthedocs.io/en/latest/

**Comment by jezdez** [comment]
Sorry this has been broken due to changes in the way RTD handles GitHub webhooks. I've updated the GitHub webhook again and this should work as expected again.

**Comment by jdufresne** [comment]
Thanks!
