### ISSUE TITLE
Pip-tools 3.6.0 release aprovement

### ISSUE THREAD

**Issue by atugushev** [jazzband/roadies#141]
I've prepared 3.6.0 release but there is still no aprovement for it. Any issues with the release?

/cc @vphilippon

**Comment by jezdez** [comment]
Thanks for raising this @atugushev, let's wait and see if @vphilippon responds to the release mail first. I'll look into this at the end of the week again.

**Comment by jezdez** [comment]
@vphilippon or @davidovich that is.

**Comment by vphilippon** [comment]
Sorry, I apparently missed the email, I'll approve it shortly.

**Comment by vphilippon** [comment]
And out it is: https://pypi.org/project/pip-tools/3.6.0/

Next step will be for me to check why the mails notifications didn't go off on my phone (not only Jazzband, other stuff too). Thanks for pointing that issue I guess :)

**Comment by jezdez** [comment]
Cheers @vphilippon!

**Comment by atugushev** [comment]
@vphilippon thank you!
