### ISSUE TITLE
python-geojson Project Lead volunteer

### ISSUE THREAD

**Issue by rayrrr** [jazzband/roadies#142]
I would like to be the Project Lead for https://github.com/jazzband/python-geojson. I intend to use it in multiple projects and will keep it running and up-to-date.

**Comment by jezdez** [comment]
Hey @frewsxcv, do you concur?

**Comment by frewsxcv** [comment]
Sounds good @jezdez and @rayrrr 👍🏻

**Comment by jezdez** [comment]
Done: https://jazzband.co/projects/python-geojson

@rayrrr Also enabled PyPI releases via Jazzband.co (docs: https://jazzband.co/about/releases) in https://github.com/jazzband/python-geojson/pull/123.

In short:

- once configured, any Git tag pushed to the repo will trigger the CI process
- as part of the CI process a release will be done to the Jazzband site
- project leads will receive an email to review the release and confirm it
- if confirmed, the release files are pushed to PyPI
