### ISSUE TITLE
Project leads for django-analytical

### ISSUE THREAD

**Issue by jcassee** [jazzband/roadies#143]
@jezdez Who are the leads for django-analytical? If none yet, I propose @bittner, @PiDelport and myself.

Also, what would be the preferred release method? The Jazzband has some text about setting up a release process through Travis-CI. Can you set that up for us, or provide pointers?

# TODO

- [x] Add @bittner, @PiDelport, @jcassee to project leads
- [x] Update travis config with Jazzband credentials.

**Comment by jezdez** [comment]
@jcassee There are no project leads yet (see https://jazzband.co/projects/django-analytical) and I'm happy to add you all to them.

The docs for the release process is here: https://jazzband.co/about/releases

In short:

- once configured, any Git tag pushed to the repo will trigger the CI process
- as part of the CI process a release will be done to the Jazzband site
- project leads will receive an email to review the release and confirm it
- if confirmed, the release files are pushed to PyPI

**Comment by jezdez** [comment]
This was fixed in https://github.com/jazzband/django-analytical/commit/c7f8dc21ad3b51238461dfa6eb739d13c0031fce. @jcassee Let me know if you have any more questions!

**Comment by jcassee** [comment]
Thanks! We'll try and make a release shortly.
