### ISSUE TITLE
Jazzband login broken

### ISSUE THREAD

**Issue by poswald** [jazzband/roadies#144]
The url https://jazzband.co/account/login returns the following:
```
Error
Looks like something went wrong.

Please open an issue for the roadies if the problem persists.
```

**Comment by jezdez** [comment]
Ah, thanks, that's a regression from when I changed auth backends, fix coming..

**Comment by jezdez** [comment]
Fixed in https://github.com/jazzband/website/commit/95209e90297f395cb26f3332d1f7d6e94a7da405.
