### ISSUE TITLE
django-ical project maintenance

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/roadies#146]
Hey,

I just updated some test settings in the django-ical project and noticed that there is no maintainer for the project to manage the releases.

https://github.com/jazzband/django-ical
https://jazzband.co/projects/django-ical

If you'd like, I can take care of it. I'm already maintaining django-axes and think that the django-ical could use some small updates and CI work for code quality gates and coverage as well as Python 3 support.

**Comment by aleksihakli** [comment]
@jezdez @cleder @pinkerton would you be OK with me as a maintainer for this project?

**Comment by cleder** [comment]
:+1:

**Comment by jezdez** [comment]
@aleksihakli Done!
