### ISSUE TITLE
Transferring a project to Jazzband when the original author has gone AWOL

### ISSUE THREAD

**Issue by richardbarran** [jazzband/roadies#150]
Hi,
I've been following [django-sortedm2m](https://github.com/gregmuellegger/django-sortedm2m), as I have an app of my own that depends on it. 

There's has been no development on this project since 2017.

[A ticket has been opened to enquire as to the status of the project](https://github.com/gregmuellegger/django-sortedm2m/issues/112), and the original author has been pinged several times, but as far as I know he/she has never responded.

So... I believe that the project in question would thrive in the Jazzband universe: it's popular, has several contributors, and people want to contribute code to it today. And such a move has already been suggested by various people on the sortedm2m issues pages.

**But** there would be - apparently - no approval from the original maintainer, if the codebase was copied/duplicated into Jazzband.

Pypi have a process in place to release and re-use project names when the original owner walks away (PEP 541), but as far as I can tell there is no equivalent set up for Jazzband.

So I want to enquire as to how Jazzband members and roadies feel about taking on a project _without_ the approval of the current maintainer, before I make a formal proposal to move this project over.

I look forward to your comments.

**Comment by jezdez** [comment]
I'm afraid, this will need approval from @gregmuellegger. I'll ping him on Twitter, too.

**Comment by gregmuellegger** [comment]
Feeling rather sorry for blocking all this by lack of time and involvement in the Django-universe in the last years (and basically wasting working hours of other people by not watching my GitHub feeds). So I'm rather happy if it would be adopted.

Go ahead and thanks for taking the time and efforts on you. 🙇

**Comment by jezdez** [comment]
@gregmuellegger In that case, please join the Jazzband GitHub org and simply transfer the repo to the organization using GitHub's own transfer tool in the repo settings. Once that's done, @richardbarran can take it from there.

**Comment by jezdez** [comment]
@gregmuellegger You can join on https://jazzband.co/ by clicking "Login and join" and follow the instructions.

**Comment by richardbarran** [comment]
Thanks @gregmuellegger.
I'm happy to help out with the transfer of the project over to Jazzband if necessary (although I'd rather not become the project lead, as I'm already involved in several other projects).

**Comment by clintonb** [comment]
@gregmuellegger would you add `jazzband` as a PyPI maintainer so we can (eventually) create releases? https://jazzband.co/about/releases

**Comment by gregmuellegger** [comment]
Done!

**Comment by jezdez** [comment]
The package has been transfered and further todos are tracked in #152. Thank you all for working on this!
