### ISSUE TITLE
django-model-utils project maintenance

### ISSUE THREAD

**Issue by charettes** [jazzband/roadies#151]
The https://github.com/jazzband/django-model-utils package already has @carljm as a maintainer but given there was no release for more than a year and my current employer actively uses this package I'd volunteer to become a lead as well.

I recently attempted to release 3.2.0 https://github.com/jazzband/django-model-utils/commit/d3d0881de02b1b7d16d1ca5d2dc3674bcc098b57 but while the package was uploaded to https://jazzband.co/projects/django-model-utils/upload it is still pending approval to be release to Pypi.

**Comment by carljm** [comment]
Sorry for slow approval, must have missed an email. Strongly in favor of adding @charettes as project lead, since I am not using this package.

**Comment by jezdez** [comment]
@carljm Thanks for the reply!

@charettes I added you as a lead dev, too. See https://jazzband.co/projects/django-model-utils for the releases. Mind you, it seems for 3.2.0 only the tarball got released to PyPI, so doing this for the whl file would be a sensible step.

**Comment by carljm** [comment]
Thanks @jezdez! I thought I released both files, but seems the `.whl` didn't go through. Did it again, looks good now.
