### ISSUE TITLE
Autodeploy failing due to "python-geojson" GitHub repo & "geojson" PyPi package naming mismatch

### ISSUE THREAD

**Issue by rayrrr** [jazzband/roadies#155]
I'm trying to release [python-geojson](https://github.com/jazzband/python-geojson) 2.5.0. However, [on PyPi](https://pypi.org/project/geojson/), the package's official name is just plain `geojson`. Since the upload URL on jazzband.co doesn't match that, Travis CI is throwing this error on the deploy step:

```
HTTPError: 400 Client Error: The filename for 'python-geojson' must start with 'python-geojson'. for url: https://jazzband.co/projects/python-geojson/upload
```

The upload URL most likely needs to be changed to https://jazzband.co/projects/geojson/upload

The failed Travis build is here: https://travis-ci.org/jazzband/python-geojson/jobs/560304832

Please assist, thanks!

I am hoping that changing the upload URL to `https://jazzband.co/projects/geojson/upload` will be all that's needed.

**Comment by rayrrr** [comment]
@jezdez sorry to bother you but since you were the one who set up the autodeploy stuff for `python-geojson` (aka `geojson`) in https://github.com/jazzband/python-geojson/pull/123 a few months back, do you have the bandwidth for this quick fix?

**Comment by rayrrr** [comment]
FYI I changed the URL in the repo I maintain...giving a URL not found error now, but still figuring that making the change on the jazzband.co side will resolve this.

**Comment by rayrrr** [comment]
FWIW here are the [release notes](https://github.com/jazzband/python-geojson/blob/master/CHANGELOG.rst#250-2019-07-18) for the version I'm trying to deploy to PyPi.

**Comment by rayrrr** [comment]
@jezdez sorry to keep bugging you but you're the only roadie I know...please put some eyes on this when you can, I am hoping it will be a quick fix.

**Comment by aleksihakli** [comment]
Would it be sensible to have 2-3 roadies in the Jazzband? At the moment our bus factor is quite high and there are dozens of projects that are dependant on one persons resources.

**Comment by jezdez** [comment]
Hey all, sorry for the delay, I was on vacation and had to catch up with paid work, first.

**Comment by jezdez** [comment]
@rayrrr Yeah, this is basically a misalignment between Jazzband project names (derived from the GitHub repo) and the package distribution name (the one specified in setup.py) and is an oversight at least and maybe a bug in the PyPI index implementation of the Jazzband site.

Since the CI process will always try to upload files depending on the package distribution name (it's what PyPI later will require as well after all), I think we'll need to enact a new rule that repos need to have the same name as the package distributions to stay consistent.

The alternative fix to loosen the name validation on upload would defeat its purpose since it would simply open the doors to upload files that will later be invalid when deploying to PyPI.

So I'll rename the GitHub repo and Jazzband project now, the good news is, GitHub will just set up redirects, so no links are lost.

**Comment by jezdez** [comment]
Okay done, https://github.com/jazzband/geojson and https://jazzband.co/projects/geojson.

I've also to re-tagged 2.5.0 with the URL changes to trigger a new deploy.

@rayrrr You should have received notifications for the new release.

**Comment by rayrrr** [comment]
@jezdez, thank you for getting around to this, and keep gettin that money! :)

I did in fact receive the new release notifications, but sadly we're not out of the woods yet. I am now getting PyPi upload errors trying to deploy 2.5.0 via the Jazzband website:

**Release of geojson-2.5.0.tar.gz failed.**

**Standard output**

**Uploading distributions to https://upload.pypi.org/legacy/ Uploading geojson-2.5.0.tar.gz 0%| | 0.00/41.2k [00:00<?, ?B/s] 19%|█▉ | 8.00k/41.2k [00:00<00:01, 24.9kB/s] 100%|██████████| 41.2k/41.2k [00:01<00:00, 39.5kB/s] NOTE: Try --verbose to see response content.**

**Standard error**

**HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/**

I saw both a "wheel" file and a "tar.gz" file on Jazzband.co, and tried to deploy both, and got the same failure with both. _Should_ I be deploying both in those situations? Either way, it looks like more roadie plumbing is needed to get this shipped to PyPi.

**Comment by aleksihakli** [comment]
We ran into this a while back, it was a result of the rST files having faulty syntax and PyPI bouncing them due to it. I fixed the syntax and rereleased and the PyPI upload went smooth after that.

**Comment by aleksihakli** [comment]
Running `rstvalidator` gives the following output:

```
$ python -m rstvalidator README.rst
README.rst
Title underline too short.
Title underline too short.
Title underline too short.
Title underline too short.
```

And checking the [`README.rst`](https://raw.githubusercontent.com/jazzband/geojson/9ef885b/README.rst) shows that the following titles have too short underlines:

```rst
map_geometries
~~~~~~~~~~

Default and custom precision
~~~~~~~~~~~~~~~~~
```

Fixing them results in `rstvalidator` running smoothly :)

**Comment by rayrrr** [comment]
@aleksihakli that fixed it! Thanks very much for your unofficial roadie work.
