### ISSUE TITLE
Proposing jsonmodels

### ISSUE THREAD

**Issue by beregond** [jazzband/roadies#158]
Hi all,

I have a project -> https://github.com/beregond/jsonmodels/ that I'd like jazzband took care of - I cannot maintain anymore - too little time lately. 

Tell me what you think, or what is to be polished, so we could then proceed with transfer. :)

**Comment by jezdez** [comment]
Interesting, this looks pretty good in terms of guidelines, feel free to just transfer the repo to the Jazzband GitHub org via the GitHub repo settings. A separate tickets with further TODOs is automatically created once the transfer is done.
