### ISSUE TITLE
contextlib2 as a JazzBand project?

### ISSUE THREAD

**Issue by ncoghlan** [jazzband/roadies#16]
At the moment, I'm a single point of failure for new releases of contextlib2, the backport of the standard library's contextlib module to earlier Python versions. That's normally not a major problem (it's not like it needs to be updated very often), but it does mean it can lag behind the standard library version for quite a while after a new Python release goes out, and problems specific to the backport can take some time to get fixed (even though merging the PR is just a click of a button, actually spinning the release still takes additional work).

I'm currently in the process of migrating the project from BitBucket to GitHub and Travis CI for easier collaboration. Once it's here, would it be a suitable candidate for inclusion?

- [x] fix links in docs and readme (@jezdez)
- [x] enable coveralls/codecov/etc (@jezdez)
- [x] enable travis-ci/other CI (@jezdez)
- [x] Should auto release via Travis be enabled? (@ncoghlan)?
- [x] add "jazzband" user to PyPI entry (and answer if auto release via Travis should be enabled) (@ncoghlan)
- [x] add "jazzband-bot" as maintainer to ReadTheDocs project (@ncoghlan)

**Comment by jezdez** [comment]
So sorry for the slow response, I think contextlib2 is an excellent project for Jazzband, especially given its background in Python core. I haven't fully automated the setup, but if you want we can schedule some time to do it. Once set up, the release process will be fully automated.

**Comment by ncoghlan** [comment]
This is its current home on GitHub: https://github.com/ncoghlan/contextlib2

The PyPI release is up to date for the time being - I did a release after finally figuring out the compatibility problem that was keeping ExitStack from working with old-style classes.

In moving the project over to jazzband, the main thing I'd be looking to do is to have additional folks with the power to make releases to PyPI - automation would be a nice bonus, but definitely not essential (now that I've sorted out the old-style class problem, I'd expect the next release to be after 3.6 comes out, and at the moment that will just add the AbstractContextManager ABC).

**Comment by jezdez** [comment]
@ncoghlan Makes sense to me. I have to say though that Jazzband isn't a guarantee that others will help with the project automatically. You'll just have a better story to tell when others ask about the onboarding to the project.

For the release process I'm working on an improved and more secure workflow at the moment. Right now, deploys to PyPI are done via successful test runs on Travis via their [PyPI integration](https://docs.travis-ci.com/user/deployment/pypi). The release happens automatically once a git tag is pushed, so there is room for abuse, although there hasn't been any reported incident for any of the Jazzband project I feel obliged to mention the current limitations. The new system works a tad different by uploading the release from Travis-CI to Jazzband.co first and then push it to PyPI once a manager (a new role in the Jazzband future) confirms the release with the press of a button. That way I think I'll be able to close the gap of potential abuse.

**Comment by jezdez** [comment]
I've opened https://github.com/ncoghlan/contextlib2/pulls FYI

**Comment by ncoghlan** [comment]
Thanks! Looking at the issue list reminded me that there was a bug fix for 3.5 that I haven't got around to backporting yet: https://github.com/ncoghlan/contextlib2/issues/7

Perhaps it would make sense to migrate over to jazzband first, and then do a 0.5.4 release with that change via the Jazzband process?

**Comment by jezdez** [comment]
@ncoghlan Works for me, I've added a bunch of tasks to the issue description above and assigned those that I can't do to you. Lemme know if you have any questions.. :)

**Comment by ncoghlan** [comment]
+1 to auto-release via Travis - I guess that will need an entry in the README or docs explaining the implications for tagging releases, and what needs to be in place before actually pushing the tag to GitHub.

**Comment by ncoghlan** [comment]
OK, jazzband now has maintainer access on PyPI, and jazzband-bot has access on RTD.

**Comment by jezdez** [comment]
@ncoghlan Ok, I've sent the PR with the changes for the Jazzband move. Now would be the time for you to transfer the repo to the **jazzband** organization. I then can enable the various services.

**Comment by ncoghlan** [comment]
The transfer request failed with "You don’t have admin rights to jazzband", so I've sent you a collaborator request for the contextlib2 repo, and will see if I can grant you sufficient privileges to initiate the transfer (otherwise I may be able to transfer it to you, and then you push it to the jazzband org)

**Comment by jezdez** [comment]
@ncoghlan Ah, right, I assumed you already joined the Jazzband on https://jazzband.co. Once you've done that you can do the transfer.

**Comment by ncoghlan** [comment]
Done! I also enabled Roadies access as part of the transfer.

**Comment by jezdez** [comment]
Okay, Landscape.io and Travis-CI handled the move gracefully and kept it enabled, I enabled Coveralls manually again.

I'll now set up the PyPI release via Travis-CI on pushing a git tag and send a PR for you to review. I'm not sure how you want to document that behavior in the README, so far no Jazzband has publicized this in the README, so not sure.

**Comment by ncoghlan** [comment]
Nice! I'll figure out documentation for the release process when I put the 0.5.4 release together - the main reason I want to write a checklist for it is that contextlib2 releases tend to be so far apart that *I* need a written reminder of how to do it :)

I'll also note the migration to Jazzband in the 0.5.4 release notes - thanks for setting up the org!

**Comment by jezdez** [comment]
@ncoghlan No problem, glad I was able to help :)
