### ISSUE TITLE
PyPI deployments for django-ical

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/roadies#160]
At the moment the django-ical package does not have the Jazzband registry setup for PyPI releases:

- https://github.com/jazzband/django-ical
- https://jazzband.co/projects/django-ical
- https://pypi.org/project/django-ical/

**Comment by jezdez** [comment]
@aleksihakli Hey, so I haven't moved django-ical to use setuptols_scm yet, so when you do the releases make sure to update the version numbers in the files manually please. Or.. move to setuptools_scm like other Jazzband projects.

**Comment by aleksihakli** [comment]
Added setuptool_scm, fixed some rST styling and made a new release through the Jazzband site to PyPI.

The RTD releases don't seem to be in sync yet: https://readthedocs.org/projects/django-ical/

**Comment by jezdez** [comment]
@aleksihakli Thanks! I've fixed RTD by adding a webhook, too.

**Comment by aleksihakli** [comment]
Seems like RTD requires the package to be installed in the environment for smooth builds: https://readthedocs.org/projects/django-ical/builds/9573786/

Do you happen to have an obvious solution for Sphinx builds with the `setuptools_scm` version fetching? I'm not too familiar with the RTD CI system.

**Comment by jezdez** [comment]
Yeah, RTD has an option to install the package during the build, which I enabled and that fixed that error. Sadly there was another showing up instead: https://readthedocs.org/projects/django-ical/builds/9575137/

I had to also move the RTD project to be built on Python 3 since setup.py used a Python 3 only feature (`open(.., encoding="utf-8")`).

**Comment by aleksihakli** [comment]
Yeah, I try to boobytrap all new releases with Python 3 only code, it adds a certain incentive for Python 2 deprecation.

Thanks for the fixes and help, everything seems to be in order infrastructure-wise for the project now :)
