### ISSUE TITLE
PyPI deployments for django-embed-video

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/roadies#161]
At the moment the django-embed-video package does not have the Jazzband registry setup for PyPI releases:

https://github.com/jazzband/django-embed-video
https://jazzband.co/projects/django-embed-video
https://pypi.org/project/django-embed-video/

**Comment by jezdez** [comment]
This is currently blocked by the fact that we don't have access to the PyPI project yet.

@yetty @CedricCarrard would one of you mind adding the `jazzband` user with a maintainer role on https://pypi.org/manage/project/django-embed-video/collaboration/ please?

**Comment by yetty** [comment]
@jezdez jazzband has been added.

**Comment by jezdez** [comment]
@yetty Thanks!

**Comment by aleksihakli** [comment]
Is it possible to check the RTD builds?

https://readthedocs.org/projects/django-embed-video/builds/

It seems like the webhook might have gone sour as the last build was 10 months ago and there have been new commits to master since that.

The RTD requires updating to a newer Sphinx and Python version, but the current codebase breaks builds on Sphinx >= 2 and functions correctly with Sphinx 1.7.9 and Python 2.7.

**Comment by jezdez** [comment]
I just noticed there was never a ticket to track the adoption of django-embed-video, this was at the time when we had trouble with GitHub ratelimiting us. Lemme open a ticket about this.

**Comment by jezdez** [comment]
@aleksihakli I've opened #163.

**Comment by aleksihakli** [comment]
@jezdez seems like the RTD webhook might not be firing correctly as master and 1.3 aren't building for django-embed-video.
