### ISSUE TITLE
Add jwhitlock as lead for django-nose, enable PyPi

### ISSUE THREAD

**Issue by jwhitlock** [jazzband/roadies#165]
To complete the guidelines for project django-nose (issue #154), please add me as a project lead, and enable creating tagged builds for upload to PyPI.

We're due for a 1.4.7 release, to note Django 2.2 support and to update the PyPI docs for Jazzband, so I should be able to test out the process soon.

**Comment by jezdez** [comment]
@jwhitlock Let me know when you do the first release so I can help out if needed. 😻
