### ISSUE TITLE
Request: add rtpg as lead for django-floppyforms

### ISSUE THREAD

**Issue by rtpg** [jazzband/roadies#166]
To complete the guidelines for project django-floppyforms (issue #159 ), please add me as a project lead, and enable creating tagged builds for upload to PyPI.

The discussion on that issue will show that I was the one to originally request transferring this project over to jazzband to the original maintainer (and I had been maintaining a branch supporting Django 1.11 in a [PR of the project](https://github.com/jazzband/django-floppyforms/pull/196))

**Comment by jezdez** [comment]
@rtpg Please let me know when you do the first release so I can help if needed. 😻
