### ISSUE TITLE
Permission for making release of Django Authority

### ISSUE THREAD

**Issue by safwanrahman** [jazzband/roadies#17]
I have made a Pull Request. can review? 
https://github.com/jazzband/django-authority/pull/48

Will be glad to get the permission.

**Comment by jezdez** [comment]
Ah, cool, I just saw this after the PR. I'll set automatic releases asap as described on https://jazzband.co/about/releases

**Comment by safwanrahman** [comment]
@jezdez Update?

**Comment by jezdez** [comment]
Hey @safwanrahman, I thought I'd get to finish my new plan for releases in time, but I failed and will enable the old/current way for authority now.

**Comment by jezdez** [comment]
@safwanrahman Okay done, please do a proper release check again, e.g. update the changelog with all changes that happened since the last release etc. Then create a new git tag 0.11 and push it to GitHub. The rest will be automated and released from Travis to PyPI automatically.

**Comment by jezdez** [comment]
Closing this issues since I've given everyone the ability to release django-authority.
