### ISSUE TITLE
Can't join the group 

### ISSUE THREAD

**Issue by ZuluPro** [jazzband/roadies#18]
As your the website ask me, I open an issue:
I logged in with GitHub this afternoon and had an error after give permissions.
This make me the same thing tonight

**Comment by ZuluPro** [comment]
@jezdez Any news ?

**Comment by jezdez** [comment]
@ZuluPro Sorry, there seems to be a bug with the latest code of the site, I'll look into it.

**Comment by ZuluPro** [comment]
Hello @jezdez : Any news ?

**Comment by sobolevn** [comment]
+1 same for me

**Comment by jezdez** [comment]
Thanks to @sobolevn this is now fixed. Cheers!
