### ISSUE TITLE
Finish move of django-admin2

### ISSUE THREAD

**Issue by jezdez** [jazzband/roadies#19]
- [x] fix links in docs and readme (@jezdez, PR coming up)
- [x] enable coveralls (@jezdez)
- [x] enable travis-ci (@jezdez)
- [x] add jazzband to PyPI entry (@pydanny)
- [x] add jazzband-bot to ReadTheDocs project (@pydanny)
- [x] Should auto release via Travis be enabled? (@andrewsmedina and @galuszkak)?

**Comment by jezdez** [comment]
PR with doc fixes: https://github.com/jazzband/django-admin2/pull/441

**Comment by pydanny** [comment]
I added Jazzband to the PyPI entry.

I don't believe auto-release via Travis should be enabled, but @andrewsmedina and @galuszkak are much better equipped to answer that question.

**Comment by pydanny** [comment]
I added `jazzband-bot` to ReadTheDocs.

**Comment by andrewsmedina** [comment]
@pydanny I believe that we can enable release via Travis when a tag is set, using "on: tag" conditional: https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

@galuszkak what do you think about it?

**Comment by galuszkak** [comment]
I'm in favor of that. If this is based on tag & branch & passing tests then that sounds great. 

One question because I have lack of knowledge in that area. Will this do beside pypi release also new documentation release on readthedocs.org ?

**Comment by andrewsmedina** [comment]
@galuszkak the documentations is automatically released by read the docs. Auto release via travis will publish  the django-admin2 package in pypi.

**Comment by galuszkak** [comment]
Awesome. Then I'm still in favor of adding that autorelease feature in Travis.

**Comment by jezdez** [comment]
Ok, I'll set it up

**Comment by jezdez** [comment]
@pydanny Can you add the "jazzband" user to the PyPI project please?

**Comment by pydanny** [comment]
@jezdez Done!

**Comment by jezdez** [comment]
@pydanny Great, I've enabled it
