### ISSUE TITLE
Integrate / collaborate with django-cc

### ISSUE THREAD

**Issue by blueyed** [jazzband/roadies#2]
There is a new initiative to have [Django Contributing Commons (CC)](https://github.com/codingjoe/django-cc).

I think it makes sense to collaborate and possibly integrate/use it for jazzband projects (by default).

/cc @codingjoe @jpic

**Comment by codingjoe** [comment]
Tho Django CC isn't quite ready, it would be cool to have some early adopters. It's certainly better than having no contributing guide.

**Comment by codingjoe** [comment]
I still would be cool to have a commend contributing guide, but django-cc is no longer maintained. We would need to pick it up again. Maybe create something for jazzband. I don't know. I'll close this for now.

**Comment by jpic** [comment]
Works as is for me, keep up the great work :+1:
