### ISSUE TITLE
Move django-debug-toolbar to Jazzband

### ISSUE THREAD

**Issue by jezdez** [jazzband/roadies#20]
Hi @robhudson, @dcramer, @aaugustin,

Since I wasn't sure what we ended up deciding, if at all, I just wanted to open this issue to track potential steps needed, feel free to join the Jazzband (on https://jazzband.co/) and then edit the following list yourself.

- [x] fix links in docs and readme
- [x] enable coveralls/codecov/etc
- [x] enable travis-ci/other CI
- [x] add jazzband to PyPI entry (and answer if auto release via Travis should be enabled)
- [x] add jazzband-bot to ReadTheDocs project

**Comment by dcramer** [comment]
I'll defer to everyone else. I tbh don't really have any time (or much care) to be involved anymore. Definitely +1 on the direction though.

**Comment by aaugustin** [comment]
I'm OK with this (or with making the DDT a Django project, per the recent DEP -- either option works for me).

**Comment by jezdez** [comment]
@aaugustin Personally I'm not involved with the new Django DEP process so can't say if it's a sensible replacement for an own GitHub organization and maintainer team.

But I **do** have experience with onboarding apps into the Django organization and removing apps from contrib (formtools, localflavor) into separate repos and found it problematic in terms of getting enough people to help out.

Since Jazzband's concept includes the complete removal of a threshold for contributing I would say it's more liberal compared to anything that the Django team is willing and able to offer. I'm not saying that it's better, but simply a different style of project management. Jazzband has currently [128 members,](https://jazzband.co/members) with a small part of active people (~15-20%), but the key to Jazzband here is the ability to on-board new members using self-service mechanisms. We all know OSS and especially "social coding" isn't a system that retains contributors forever, so that's why I believed the barrier of entrance was the most important part to simplify.

So all in all, I'm more in favor of moving DDT to Jazzband, but that's just me and I admit I'm biased.

@robhudson Any opinion on this?

**Comment by robhudson** [comment]
I'm for whatever will help let debug toolbar survive and continue to be useful to people as Django moves forward. If right now the best option is jazzband, then I'm 👍.

**Comment by aaugustin** [comment]
Indeed Jazzband is a better match for the kind of contributions the toolbar gets. Let's move it here.

**Comment by jezdez** [comment]
Awesome, I'll start to work on the TODOs in this ticket

**Comment by jezdez** [comment]
Okay, I've done all of those, except for Transifex where I'm not sure if anything needed to be changed. Let me know if you see any trouble with this..

**Comment by jezdez** [comment]
Oh BTW, the URL is: https://github.com/jazzband/django-debug-toolbar

**Comment by aaugustin** [comment]
Cool. Thank you so much for taking care of the migration.

**Comment by jezdez** [comment]
@aaugustin My pleasure 💐
