### ISSUE TITLE
Enable requires.io for @jazzband/django-debug-toolbar

### ISSUE THREAD

**Issue by webknjaz** [jazzband/roadies#24]
As asked in jazzband/django-debug-toolbar#863, I'm documenting this issue to track PR jazzband/django-debug-toolbar#858 improvements.
It is required that @jazzband/roadies enable repositories from this organization @ required.io, normal member cannot do this.

Also it would be nice to enable notifications via PR here [here](https://requires.io/github/jazzband/hooks/), if you didn't do this yet :)

P.S. I've already changed the link in README: jazzband/django-debug-toolbar@06e09ac

**Comment by jezdez** [comment]
Awesome, thanks!

I've enabled requires.io for django-debug-toolbar and set up a PR hook for it. I did *not* enable requires.io for all Jazzband projects since I first want to see how this goes.
