### ISSUE TITLE
Please add the readthedocs webhook

### ISSUE THREAD

**Issue by camilonova** [jazzband/roadies#25]
To this https://github.com/jazzband/django-axes

Thanks.

**Comment by jezdez** [comment]
Sure, can you add **jazzband-bot** as a maintainer to the RTD project on https://readthedocs.org/dashboard/django-axes/users/?

**Comment by camilonova** [comment]
Done

**Comment by jezdez** [comment]
Awesome, I've enabled it.

**Comment by camilonova** [comment]
Thanks
