### ISSUE TITLE
Requesting django-push-notifications

### ISSUE THREAD

**Issue by jleclanche** [jazzband/roadies#26]
As discussed on IRC, I'm the author of django-push-notifications and I would like to have the project join the band.

https://github.com/jleclanche/django-push-notifications

**Comment by jezdez** [comment]
Assuming you follow the [guidelines](https://jazzband.co/about/guidelines) this should be good to go. I recommend creating a Sphinx documentation and move the README into that, then create a ReadTheDocs project. Once you've moved the repo to the Jazzband organization the Jazzband bot will automatically open a ticket here in the roadies repo to track TODOs for the Jazzband adoption.

**Comment by jleclanche** [comment]
@jezdez Pinging this again, I don't think I noticed your answer since it was a few months out :) But I remember us talking on IRC. I believe the project adheres to the guidelines already, although it doesn't use RTD for documentation (there is only a README which is picked up by pypi).

I recently moved the project to the django-push-notifications org but I'm happy to move it to jazzband instead...

**Comment by jezdez** [comment]
There are a few things to fix and the README is easy enough to move to a Sphinx project after the fact. Mind do the transfer? There will be a separate ticket to track the transfer TODOs.

**Comment by jleclanche** [comment]
Yeah, sure thing.

**Comment by jleclanche** [comment]
How do I do the transfer? If I try to transfer it to the org, I don't have permission.

**Comment by jezdez** [comment]
@jleclanche First, join the organization by going to https://jazzband.co, login with GitHub and join there.

**Comment by jezdez** [comment]
FTR, you'll get an invite from GitHub to join the organization.

**Comment by jleclanche** [comment]
Hmm?

![image](https://user-images.githubusercontent.com/235410/36061796-69fd8e40-0e68-11e8-8088-86ac84719640.png)

**Comment by jezdez** [comment]
Sigh, looking..

**Comment by jezdez** [comment]
Weird, can you try again?

**Comment by jleclanche** [comment]
Ok, transfer done.

https://github.com/jazzband/django-push-notifications

How can I ensure that @jamaalscarlett, @kit-cat and @matthewh still have commit access?

**Comment by jezdez** [comment]
Excellent, see #85 for the transfer TODOs. (sorry for the duplicates)

All of the current collaborators have been transferred as well but it's required for them to join Jazzband properly via jazzband.co as well. That way we don't have project specific permissions to maintain -- since everyone in the Jazzband can commit to any repo after all.

**Comment by jleclanche** [comment]
Excellent. Closing this and following up in the other issue.

**Comment by jezdez** [comment]
@jleclanche FTR I added a TODO item to ask the old collaborators to join as well.
