### ISSUE TITLE
develop default branch of `django-admin2`

### ISSUE THREAD

**Issue by andrewsmedina** [jazzband/roadies#36]
`django-admin2` uses develop branch as the default. someone can change it in the project settings?

**Comment by jezdez** [comment]
@andrewsmedina The develop branch is already set up as the default branch:

![screen shot 2016-11-09 at 09 32 33](https://cloud.githubusercontent.com/assets/1610/20131706/7a11c1b0-a65f-11e6-9477-298d1a6d0407.png)

**Comment by andrewsmedina** [comment]
@jezdez thank you!
