### ISSUE TITLE
django-widget-tweaks

### ISSUE THREAD

**Issue by kmike** [jazzband/roadies#37]
Hey, I want to move https://github.com/kmike/django-widget-tweaks to jazzband org. Are you ok with that? Did I get it right, and the required steps are:

1. CONTRIBUTING.md file with a link to jazzband and Contributor Code of Conduct?
2. setup pypi deployments via Travis (is it required?) and grant jazzband access to it;
3. transfer the repo, update links?

**Comment by jezdez** [comment]
@kmike Once you've transferred the repo to the Jazzband organization the Jazzband bot will automatically create a ticket here in the roadies repo (and assign the roadies and you) with a TODO list. The app seem to fit nicely with Jazzband.

**Comment by kmike** [comment]
Sorry, I missed your answer :) Thanks! Repository is moved; TODO list is here: https://github.com/jazzband/roadies/issues/70.
