### ISSUE TITLE
Take over djmail

### ISSUE THREAD

**Issue by mathieuhinderyckx** [jazzband/roadies#49]
The package https://github.com/bameda/djmail seems not actively maintained anymore. I have contributed a few times, leading to the latest release, and use it for several projects. However, sinc a few months the current maintainer does not reply anymore. Aso the documentation was changed with the last PR, but he has not updated the site where it is located after the merge/release. There is an open pull request from December 11th 2016, with no reply whatsoever, also after I pinged him. Would it be possible to transfer this project over to Jazzband?

The project itself is in good shape. It works with python 2/3  and all currently supported Django versions. It has automated testing with Travis CI and good documentation. I have been using it in production for a few years now. It's on PyPi and Django-packages.

**Comment by jezdez** [comment]
@mhindery The person to do the actual transfer via GitHub is the owner of the repo @bameda. I'd suggest to send him an email or some other message to ask him to move the project over to Jazzband. If they don't respond or decline I'm afraid there is nothing we can do, Jazzband doesn't want to create hostile forks of projects but always include the original authors/maintainers to increase the chance of a successful handover.

FWIW, the project seem to fit the [guidelines](https://jazzband.co/about/guidelines) close enough that adoption should be possible.

**Comment by mhindery** [comment]
I have closed this issue as he has replied to my contact attempts, and made clear that he did not abandon the project, but has been simply busy with other things the past few months.

**Comment by jezdez** [comment]
@mhindery Ah, awesome, glad to hear it 👍
