### ISSUE TITLE
IRC notifier

### ISSUE THREAD

**Issue by cyberdelia** [jazzband/roadies#5]
Dear Roadies,

A long time ago, I enabled a IRC notifier on django-pipeline, and forgot about it. And now I find it really annoying, but can't disable it, could you please be kind and remove it from django-pipeline?

Thanks for tuning my guitars.

**Comment by jezdez** [comment]
Absolutely!

**Comment by jezdez** [comment]
Done!

**Comment by cyberdelia** [comment]
Thanks!
