### ISSUE TITLE
Add AppVeyor support to pip-tools project

### ISSUE THREAD

**Issue by davidovich** [jazzband/roadies#51]
Hi, 

I would find it useful to add Windows tests to pip-tools through AppVeyor, but I am not sure what is needed from the roadies to allow this. 

Thanks!

**Comment by davidovich** [comment]
I have made progress, I will keep you posted. It seems everything is already setup to allow AppVeyor functionality.

**Comment by davidovich** [comment]
So it seems that pip-tools needs some intervention from the roadies. I guess we need to configure a post commit hook to trigger an appveyor build. Initial support in this PR: https://github.com/jazzband/pip-tools/pull/482, but that embryo is not enough.

**Comment by jezdez** [comment]
@davidovich This is now enabled. Let me know if you need anything else, like change the configuration or something.

**Comment by davidovich** [comment]
Thanks @jezdez everything works as expected. 

https://ci.appveyor.com/project/jazzband-bot/pip-tools
