### ISSUE TITLE
interest in accepting django-model-utils?

### ISSUE THREAD

**Issue by carljm** [jazzband/roadies#52]
Hi jazzband roadies! Cool project! Any interest in having django-model-utils join the band (see https://github.com/carljm/django-model-utils/issues/272)? I read the requirements and I think django-model-utils meets them: it's an established and stable project with a history of broad contributions from the community, it has documentation and good test coverage with tox/travis integration. I'm just not using the project myself anymore and no longer able to dedicate time to issues/PRs and making releases.

Let me know what you think!

**Comment by jezdez** [comment]
@carljm Sounds good to me! Once you do the transfer there will be an issue opened with a TODO list for the adoption.
