### ISSUE TITLE
Proposal move sorl-thumbnail

### ISSUE THREAD

**Issue by mariocesar** [jazzband/roadies#57]
sorl-thumbnail is a thumbnail app to help django projects perform image cropping, resize, and various image transformations. 

Will love to move the maintainance lead to @jazzband. 

- [x] CONTRIBUTING.md mentioning jazzband
- [x] README.md badge and mention

**Comment by jezdez** [comment]
@mariocesar Hey, sorry I missed you on IRC, so your first changes are good, the best thing would be to actually transfer the repo to the jazzband organization. The jazzbandbot will then open a ticket with more TODOs. Feel free to close this ticket once you've done that.

**Comment by mariocesar** [comment]
I'm not able to transfer the repo, I'm not part of the organization.

How do I get to be a member?

**Comment by jezdez** [comment]
Go to https://jazzband.co and join there.

**Comment by mariocesar** [comment]
Dobe
