### ISSUE TITLE
Integrate django-pure-pagination

### ISSUE THREAD

**Issue by jpic** [jazzband/roadies#6]
Would it be possible to maintain a fork of django-pure-pagination ? https://github.com/jamespacileo/django-pure-pagination

Seems like the most maintained one is: https://github.com/hovel/django-pure-pagination

But there's no release on PyPi. Since dependency_links is deprecated, it would be great to have a release of the fork and to maintain it in the community.

Thoughts ?

**Comment by jpic** [comment]
The maintainer woke up ^^, sorry for the noise, keep up the great work !

**Comment by jezdez** [comment]
Dang, I was too slow, apologies, holidays et al. Lemme know if you want to restart the discussion around this.
