### ISSUE TITLE
Add encrypted password of PyPI jazzband to sorl-thumbnail

### ISSUE THREAD

**Issue by Flimm** [jazzband/roadies#69]
Jazzband sorl-thumbnail is ready to auto-release on PyPI whenever a Git tag is created and pushed to GitHub. The `.travis.yml` has been modified, the only step left is to add the encrypted password.

https://github.com/jazzband/sorl-thumbnail

I have followed the instructions found at https://jazzband.co/about/releases

@mariocesar This is part of #62.

**Comment by Flimm** [comment]
@jezdez It seems that you are the only Jazzband roadie at the moment. Could you take a look at this? This issue was field over a month ago, and sorl-thumbnail hasn't had a new release on PyPI for a year and a half.

**Comment by camilonova** [comment]
I just added the password.

**Comment by camilonova** [comment]
@jezdez I copied the password from another project, but I guess the encrypted password doesn't work that way. Could you please encrypt the password and change it?

**Comment by jezdez** [comment]
@camilonova Unfortunately I can't at the moment due to an ongoing security review. I'm currently able to go into details publicly.

**Comment by blueyed** [comment]
s/able/unable/ ?

**Comment by jezdez** [comment]
@blueyed Yep, thanks, apparently just like typing ;)

**Comment by camilonova** [comment]
@jezdez how about tomorrow?

**Comment by triat** [comment]
@jezdez It's been a long time that you're working on this security review, is there any place where we can have an overview of what's going on ?

**Comment by hobarrera** [comment]
Can't you provide the password [via the travis UI](https://travis-ci.org/jazzband/roadies/settings) either?

(Upside of that is that you *can* copy-paste it without doing anytihng funky).

**Comment by GitRon** [comment]
Any news on this issue?

**Comment by pycarlos** [comment]
Hi @jezdez any news?

**Comment by camilonova** [comment]
@jezdez we are kind of stuck in here. Do you think there are more ways to work on those issues without your time?

**Comment by jezdez** [comment]
Good news everyone, I've finished the feature for the site that will simplify the release process going forward and add the required precautions to prevent malicious releases. Thanks all for the patience.

I've documented it on https://jazzband.co/about/releases.

The short version:

I've worked on a way for Jazzband members to join individual projects as "project members" and also to designate one or many of those to be "lead project members". The idea is to add a tiny bit more structure in the way Jazzband is organized right now and allow those project members to gain more powers that currently only the roadies have. As of right now I have not implemented creating Github teams for every project, but it's on my roadmap.

Once the project is set up for the process (currently a one-time-only process, but with the chance for fully automatic setup for new Jazzband projects) the "lead project members" are able to review package releases done via Travis-CI before they are released to PyPI.

More info here: https://jazzband.co/about/releases

Now I'm looking for someone or a few people who are willing to volunteer to be responsible for the release review of sorl-thumbnail. Any takers?

**Comment by pycarlos** [comment]
Hi @jezdez thank you for your help, I can be responsible but I need advice to do it because will be my first time doing that.

**Comment by camilonova** [comment]
@jezdez count me in

**Comment by jezdez** [comment]
@pycarlos I haven't seen contributions from you in the repo, so I'm just going to go with @camilonova for now only. I hope you understand.

@camilonova I've added you to the project and updated the deploy config here: https://github.com/jazzband/sorl-thumbnail/commit/efaed432f86ee2fb41081ad3dd57c66058fcaab0

Closing as fixed for now 📦

**Comment by Flimm** [comment]
Thank you @jezdez. I think it makes complete sense for Jazzband projects in general to have "lead project members" review releases to PyPI, especially since there is no barrier to joining Jazzband itself. I like it!

And thank you to @camilonova, too. sorl-thumbnail has just made its first release on PyPI in two years! Woot!
