### ISSUE TITLE
Add Tim Graham as lead on django-hosts

### ISSUE THREAD

**Issue by timgraham** [jazzband/roadies#76]
https://github.com/jazzband/django-hosts

**Comment by jezdez** [comment]
Done. I've also updated the django-hosts setup to make sure of the Jazzband uploads/release system. Once you've tagged/pushed a release and Travis-CI has uploaded the release to Jazzband, you'll get an email about it. Let me know if you find issues with it.

**Comment by timgraham** [comment]
I got the error "missing user" when trying to push a release: https://travis-ci.org/jazzband/django-hosts/jobs/304742382. I guess that's because `user: jazzband` was removed in https://github.com/jazzband/django-hosts/commit/1ec965ae11d3ea8b2b369a0a19b61ab4ea9e62dc? Thanks for your your help.

**Comment by jezdez** [comment]
Hm, this is weird, I assumed I could just remove the user when I use one of the environment variables for the PyPI deploy method for Travis-CI.

**Comment by jezdez** [comment]
@timgraham I've fixed it I think: https://github.com/jazzband/django-hosts/commit/54253d78f4d376e255fb1a36de813122c93da8f8 Can you try again?

**Comment by jezdez** [comment]
Seems to have worked. Closing as fixed.
