### ISSUE TITLE
Error happened when joining member

### ISSUE THREAD

**Issue by shangdahao** [jazzband/roadies#81]
in page https://jazzband.co/account, when I click "please join" in the paragraph：

> You're currently an inactive member
   To become an active member please join the Jazzband GitHub organization. For security reasons 
   GitHub will ask you to confirm the invitation to the Jazzband GitHub organization.

the new page shows:

> Error
   Looks like something went wrong.
   Please open an issue for the roadies if the problem persists.
   The error identifier is 701d7da985254f889edf2cc9da55ea21

I have tested with Google Chrome, Safari, Firefox, on MacOS 10.13.1, all the same errors, the error identifier is different each time.

**Comment by jezdez** [comment]
Thanks, this is fixed now.
