### ISSUE TITLE
Release django-authority to PyPi

### ISSUE THREAD

**Issue by safwanrahman** [jazzband/roadies#83]
I have merged a pull request made by @jlward that implement support of Django 1.11 also made a release to github. But it seems like only lead project members can push to Pypi.

Any roadies are able to make a push?

**Comment by jezdez** [comment]
Thanks for opening the ticket, seems like the repo never got set up correctly to do seamless releases via Travis CI (e.g. using setuptools_scm) etc. I just did that and did a 0.12 release to PyPI manually. For that to happen I had to redo the 0.12 tag, sadly. @jlward Please be aware that this happened.

With regard to the current release 0.13 and the future of it, I've just fixed a bunch of things in the CI setup which means that it matches the current Jazzband release procedure:

- when a new git tag is pushed to github and travis passed it'll do a release to the jazzband site
- the project leads will get an email requesting a review of the release and can push the release to PyPI on the jazzband site
- @jlward and me have been set up as project leads as it has been in the past
- we use setuptools_scm now, which means no files need to be updated to get the new version ready, but the changelog needs to be updated still

While writing this comment, the 0.13 release has been [pushed by Travis-CI](https://travis-ci.org/jazzband/django-authority/jobs/334363263) to the jazzband for @jlward and me confirm the release. Closing this as fixed.

**Comment by jezdez** [comment]
@jlward I've released both files of the 0.13 release.

**Comment by jezdez** [comment]
@jlward BTW, for more info for the current state of project release via Jazzband see https://jazzband.co/about/releases

**Comment by safwanrahman** [comment]
Thanks @jezdez and @jlward
