### ISSUE TITLE
Issue publishing to Pypi

### ISSUE THREAD

**Issue by camilonova** [jazzband/roadies#84]
I wanted to issue a release and this error is happening:

![screen shot 2018-02-07 at 9 30 32 am](https://user-images.githubusercontent.com/202559/35921761-95a10d46-0be9-11e8-87d2-fbfeb787de27.png)

https://travis-ci.org/jazzband/django-constance/jobs/338512999

Thanks.

**Comment by jezdez** [comment]
Ah, yeah, it's not set up to work with the new project releases yet. Upcoming..

**Comment by jezdez** [comment]
Fixed. Releases happen now via the Jazzband. Released 2.1.0: https://pypi.python.org/pypi/django-constance/2.1.0
