### ISSUE TITLE
Please let me publish django-widget-tweaks

### ISSUE THREAD

**Issue by camilonova** [jazzband/roadies#89]
Thank you.

**Comment by camilonova** [comment]
I pushed a tag and I got this:
![screen shot 2018-03-19 at 4 40 54 pm](https://user-images.githubusercontent.com/202559/37623934-676049ae-2b94-11e8-80ff-93b986084c30.png)

https://travis-ci.org/jazzband/django-widget-tweaks/jobs/355586758

Maybe something is missing?

**Comment by jezdez** [comment]
Yeah, it's not set up for releases yet, will handle it asap.

**Comment by camilonova** [comment]
@jezdez any updates?

**Comment by jezdez** [comment]
@camilonova Please remove the git tag(s) again you tried to release and re-tag with the commit I just pushed.

**Comment by camilonova** [comment]
@jezdez all done. Thank you.
